platform: linux
image_resource:
  type: registry-image
  source:
    repository: govsvc/task-toolbox
    tag: latest
inputs:
- name: github-oidc-proxy-git
- name: terraform-outputs
params:
  GITHUB_CLIENT_ID:
run:
  path: /bin/ash
  args:
    - -e
    - -c
    - |
      test_for_substring () {
        grep -F "$1" "$2" > /dev/null && echo "Found substring $1"
      }

      export API_BASE_URL=$(jq -r '.api_base_url.value' terraform-outputs/outputs.json)
      export OAUTH_STATE=$RANDOM$RANDOM

      export TARGET_URL="$API_BASE_URL/authorize?client_id=$GITHUB_CLIENT_ID&state=$OAUTH_STATE&redirect_uri=http://localhost:1234/"
      echo "Probing $TARGET_URL"
      curl $TARGET_URL -f -w '%{redirect_url}' > redirect_url

      echo "redirect_url: $(cat redirect_url)"

      test_for_substring 'github.com' redirect_url
      test_for_substring "state=$OAUTH_STATE" redirect_url
      test_for_substring "client_id=$GITHUB_CLIENT_ID" redirect_url

      export TARGET_URL="$API_BASE_URL/.well-known/jwks.json"
      echo "Probing $TARGET_URL"
      curl $TARGET_URL -f > jwks.json
      jq -e '(.keys | length) >= 1' jwks.json > /dev/null \
        && echo "Found populated 'keys' array"

      export TARGET_URL="$API_BASE_URL/.well-known/openid-configuration"
      echo "Probing $TARGET_URL"
      curl $TARGET_URL -f > openid-configuration.json
      jq -e '.issuer == env.API_BASE_URL' openid-configuration.json > /dev/null \
        && echo "Found correct 'issuer'"
