display:
  background_image: ((background-image))

resources:

- name: github-oidc-proxy-git
  icon: github
  type: git
  source:
    branch: ((github-oidc-proxy-git-branch))
    uri: git@github.com:alphagov/github-oidc-proxy.git
    private_key: ((github-oidc-proxy-git-ssh-private-key))

jobs:

- name: update-pipeline
  serial: true
  plan:
  - get: github-oidc-proxy-git
    trigger: true
  - set_pipeline: self
    file: github-oidc-proxy-git/ci/deploy.yml
    vars:
      github-oidc-proxy-git-branch: ((github-oidc-proxy-git-branch))
      background-image: ((background-image))
      meta-suffix: ((meta-suffix))

- name: deploy-staging
  serial: true
  plan:
  - get: github-oidc-proxy-git
    trigger: true
    passed: [update-pipeline]
  - task: build-dist
    params:
      JWKS_PUBLIC_KEY: ((staging-jwks-public-key))
      JWKS_PRIVATE_KEY: ((staging-jwks-private-key))
    file: github-oidc-proxy-git/ci/tasks/build-dist.yml
  - task: apply-terraform
    params:
      TF_VAR_GITHUB_CLIENT_ID: ((staging-github-client-id))
      TF_VAR_GITHUB_CLIENT_SECRET: ((staging-github-client-secret))
      TERRAFORM_STATE_BUCKET: ((staging-terraform-state-bucket))
      TERRAFORM_STATE_REGION: ((staging-terraform-state-region))
      ENVIRONMENT_NAME: staging((meta-suffix))
      DEPLOYER_ROLE_ARN: ((staging-deployer-role-arn))
    file: github-oidc-proxy-git/ci/tasks/terraform.yml
  - task: smoke-test
    params:
      GITHUB_CLIENT_ID: ((staging-github-client-id))
    file: github-oidc-proxy-git/ci/tasks/smoke-test.yml

