display:
  background_image: ((background-image))

resources:

- name: github-oidc-proxy-git
  icon: github
  type: git
  source:
    branch: ((github-oidc-proxy-git-branch))
    uri: ((github-oidc-proxy-git-uri))
    private_key: ((github-oidc-proxy-git-ssh-private-key))

- name: allowed-ips-git
  icon: github
  type: git
  source:
    branch: ((allowed-ips-git-branch))
    uri: ((allowed-ips-git-uri))
    private_key: ((allowed-ips-git-ssh-private-key))

jobs:

- name: update-pipeline
  serial: true
  plan:
  - get: github-oidc-proxy-git
    trigger: true
  - set_pipeline: self
    file: github-oidc-proxy-git/ci/deploy.yml
    vars:
      github-oidc-proxy-git-branch: ((github-oidc-proxy-git-branch))
      github-oidc-proxy-git-uri: ((github-oidc-proxy-git-uri))
      allowed-ips-git-branch: ((allowed-ips-git-branch))
      allowed-ips-git-uri: ((allowed-ips-git-uri))
      allowed-ips-git-tf-module-path: ((allowed-ips-git-tf-module-path))
      allowed-ips-git-tf-output-name: ((allowed-ips-git-tf-output-name))
      background-image: ((background-image))
      meta-suffix: ((meta-suffix))

- name: deploy-staging
  serial: true
  plan:
  - in_parallel:
    - get: github-oidc-proxy-git
      trigger: true
      passed: [update-pipeline]
    # - get: allowed-ips-git
     # trigger: false
  - task: build-dist
    params:
      JWKS_PUBLIC_KEY: ((staging-jwks-public-key))
      JWKS_PRIVATE_KEY: ((staging-jwks-private-key))
    file: github-oidc-proxy-git/ci/tasks/build-dist.yml
  - task: apply-terraform
    params:
      TF_VAR_GITHUB_CLIENT_ID: ((staging-github-client-id))
      TF_VAR_GITHUB_CLIENT_SECRET: ((staging-github-client-secret))
      TF_VAR_domain_root_zone_tfstate_s3_region: ((staging-domain-root-zone-tfstate-s3-region))
      TF_VAR_domain_root_zone_tfstate_s3_bucket: ((staging-domain-root-zone-tfstate-s3-bucket))
      TF_VAR_domain_root_zone_tfstate_s3_key: ((staging-domain-root-zone-tfstate-s3-key))
      TF_VAR_domain_root_zone_tfstate_id_output_name: ((staging-domain-root-zone-tfstate-id-output-name))
      TF_VAR_domain_subdomain: ((staging-domain-subdomain))
      # TF_VAR_allowed_ips: ((readonly_egress_ips))
      # TF_VAR_allowed_ips_tf_module_output_name: ((allowed-ips-git-tf-output-name))
      # ALLOWED_IPS_TF_MODULE_PATH: ((allowed-ips-git-tf-module-path))
      TERRAFORM_STATE_BUCKET: ((staging-terraform-state-bucket))
      TERRAFORM_STATE_REGION: ((staging-terraform-state-region))
      ENVIRONMENT_NAME: staging((meta-suffix))
      DEPLOYER_ROLE_ARN: ((staging-deployer-role-arn))
    file: github-oidc-proxy-git/ci/tasks/terraform.yml
  - task: smoke-test
    params:
      GITHUB_CLIENT_ID: ((staging-github-client-id))
    file: github-oidc-proxy-git/ci/tasks/smoke-test.yml
    attempts: 6

- name: deploy-production
  serial: true
  plan:
  - in_parallel:
    - get: github-oidc-proxy-git
      trigger: true
      passed: [deploy-staging]
    - get: allowed-ips-git
      trigger: false
      # passed: [deploy-staging]
  - task: build-dist
    params:
      JWKS_PUBLIC_KEY: ((production-jwks-public-key))
      JWKS_PRIVATE_KEY: ((production-jwks-private-key))
    file: github-oidc-proxy-git/ci/tasks/build-dist.yml
  - task: apply-terraform
    params:
      TF_VAR_GITHUB_CLIENT_ID: ((production-github-client-id))
      TF_VAR_GITHUB_CLIENT_SECRET: ((production-github-client-secret))
      TF_VAR_domain_root_zone_tfstate_s3_region: ((production-domain-root-zone-tfstate-s3-region))
      TF_VAR_domain_root_zone_tfstate_s3_bucket: ((production-domain-root-zone-tfstate-s3-bucket))
      TF_VAR_domain_root_zone_tfstate_s3_key: ((production-domain-root-zone-tfstate-s3-key))
      TF_VAR_domain_root_zone_tfstate_id_output_name: ((production-domain-root-zone-tfstate-id-output-name))
      TF_VAR_domain_subdomain: ((production-domain-subdomain))
      TF_VAR_allowed_ips: ((readonly_egress_ips))
      TF_VAR_allowed_ips_tf_module_output_name: ((allowed-ips-git-tf-output-name))
      ALLOWED_IPS_TF_MODULE_PATH: ((allowed-ips-git-tf-module-path))
      TERRAFORM_STATE_BUCKET: ((production-terraform-state-bucket))
      TERRAFORM_STATE_REGION: ((production-terraform-state-region))
      ENVIRONMENT_NAME: production((meta-suffix))
      DEPLOYER_ROLE_ARN: ((production-deployer-role-arn))
    file: github-oidc-proxy-git/ci/tasks/terraform.yml
  - task: smoke-test
    params:
      GITHUB_CLIENT_ID: ((production-github-client-id))
    file: github-oidc-proxy-git/ci/tasks/smoke-test.yml
    attempts: 6
